### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Troto** [StephenSwat/DnD-Spelldeck#2]
Using the command "python generate.py -c sorcerer" (Python 3.5.2) it got most of the way through with the last successful spell being "Power word stun" before throwing the following error:

Traceback (most recent call last):
  File "generate.py", line 115, in <module>
    print_spell(name, **spell)
  File "generate.py", line 61, in print_spell
    (name, header, range, time, duration, ", ".join(components), source or '', textwrap.fill(new_text, 80)))
  File "C:\Users\Toby\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u20ac' in position 268: character maps to <undefined>

I had a quick look around and it seems to be Prestidigitation that's the next sorcerer spell and it has some special characters in. Might want to look into it.

**Comment by Troto** [comment]
I'm an idiot and didn't see the output part of the command.
